package spec

var DataElements = []DataElementSpec{
	{
		TypeName: "SegmentHeader",
		Name:     "Segmentkopf",
		Version:  1,
		Type:     DEG,
		Format:   "",
		Elements: []DataElementUsageSpec{
			{
				Number:    1,
				FieldName: "ID",
				Name:      "Segmentkennung",
				Version:   1,
				Type:      DE,
				Format:    an,
				Length:    "..6",
				Status:    M,
				Count:     1,
			},
			{
				Number:    2,
				FieldName: "Number",
				Name:      "Segmentnummer",
				Version:   1,
				Type:      DE,
				Format:    num,
				Length:    "..3",
				Status:    M,
				Count:     1,
			},
			{
				Number:    3,
				FieldName: "Version",
				Name:      "Segmentversion",
				Version:   1,
				Type:      DE,
				Format:    num,
				Length:    "..3",
				Status:    M,
				Count:     1,
			},
			{
				Number:    4,
				FieldName: "Reference",
				Name:      "Bezugssegment",
				Version:   1,
				Type:      DE,
				Format:    num,
				Length:    "..3",
				Status:    C,
				Count:     1,
			},
		},
	},
	{
		TypeName: "AccountBalancesParameters",
		Name:     "Parameter Kontoumsätze/Zeitraum",
		Version:  1,
		Type:     DEG,
		Format:   "",
		Elements: []DataElementUsageSpec{
			{
				Number:     1,
				FieldName:  "MaxDaysStored",
				Name:       "Speicherzeitraum",
				Version:    1,
				Type:       DE,
				Format:     num,
				Length:     "..4",
				Status:     M,
				Count:      1,
				Limitation: ">0",
			},
			{
				Number:    2,
				FieldName: "MaxEntriesAllowed",
				Name:      "Eingabe Anzahl Einträge erlaubt",
				Version:   1,
				Type:      DE,
				Format:    jn,
				Length:    "#",
				Status:    M,
				Count:     1,
			},
			{
				Number:    3,
				FieldName: "AllAccountsAllowed",
				Name:      "Alle Konten erlaubt",
				Version:   1,
				Type:      DE,
				Format:    jn,
				Length:    "#",
				Status:    M,
				Count:     1,
			},
		},
	},
}
