package spec

var segments = []SegmentSpec{
	{
		TypeName: "AccountBalancesRequest",
		Name:     "Kontoumsätze anfordern/Zeitraum",
		Kind:     "Geschäftsvorfall",
		Id:       "HKKAZ",
		Version:  6,
		Sender:   Kunde,
		Elements: []DataElementUsageSpec{
			{
				Number:    1,
				FieldName: "Header",
				Name:      "Segmentkopf",
				Version:   1,
				Type:      DEG,
				Format:    composed,
				Length:    "",
				Status:    M,
				Count:     1,
			},
			{
				Number:    2,
				FieldName: "Account",
				Name:      "Kontoverbindung Auftraggeber",
				Version:   2,
				Type:      DEG,
				Format:    ktv,
				Length:    "#",
				Status:    M,
				Count:     1,
			},
			{
				Number:    3,
				FieldName: "AllAccounts",
				Name:      "Alle Konten",
				Version:   1,
				Type:      DE,
				Format:    jn,
				Length:    "#",
				Status:    M,
				Count:     1,
			},
			{
				Number:    4,
				FieldName: "From",
				Name:      "Von Datum",
				Version:   1,
				Type:      DE,
				Format:    dat,
				Length:    "#",
				Status:    O,
				Count:     1,
			},
			{
				Number:    5,
				FieldName: "To",
				Name:      "Bis Datum",
				Version:   1,
				Type:      DE,
				Format:    dat,
				Length:    "#",
				Status:    O,
				Count:     1,
			},
			{
				Number:    6,
				FieldName: "MaxEntries",
				Name:      "Maximale Anzahl Einträge",
				Version:   1,
				Type:      DE,
				Format:    num,
				Length:    "..4",
				Status:    C,
				Count:     1,
			},
			{
				Number:    7,
				FieldName: "ContinuationReference",
				Name:      "Aufsetzpunkt",
				Version:   1,
				Type:      DE,
				Format:    an,
				Length:    "..35",
				Status:    C,
				Count:     1,
			},
		},
	},
	{
		TypeName:    "AccountBalancesResponse",
		Name:        "Kontoumsätze rückmelden/Zeitraum",
		Kind:        "Geschäftsvorfall",
		Id:          "HIKAZ",
		ReferenceId: "HKKAZ",
		Version:     6,
		Sender:      Kreditinstitut,
		Elements: []DataElementUsageSpec{
			{
				Number:    1,
				FieldName: "Header",
				Name:      "Segmentkopf",
				Version:   1,
				Type:      DEG,
				Format:    composed,
				Length:    "",
				Status:    M,
				Count:     1,
			},
			{
				Number:    2,
				FieldName: "BookedTransactions",
				Name:      "Kontoverbindung Auftraggeber",
				Version:   1,
				Type:      DE,
				Format:    bin,
				Length:    "..",
				Status:    M,
				Count:     1,
			},
			{
				Number:    3,
				FieldName: "UnbookedTransactions",
				Name:      "Alle Konten",
				Version:   1,
				Type:      DE,
				Format:    bin,
				Length:    "..",
				Status:    O,
				Count:     1,
			},
		},
	},
	{
		TypeName:    "AccountBalancesResponse",
		Name:        "Kontoumsätze rückmelden/Zeitraum",
		Kind:        "Geschäftsvorfall",
		Id:          "HIKAZS",
		ReferenceId: "HKVVB",
		Version:     6,
		Sender:      Kreditinstitut,
		Elements: []DataElementUsageSpec{
			{
				Number:    1,
				FieldName: "Header",
				Name:      "Segmentkopf",
				Version:   1,
				Type:      DEG,
				Format:    composed,
				Length:    "",
				Status:    M,
				Count:     1,
			},
			{
				Number:    2,
				FieldName: "MaxJobs",
				Name:      "Maximale Anzahl Aufträge",
				Version:   1,
				Type:      DE,
				Format:    num,
				Length:    "..3",
				Status:    M,
				Count:     1,
			},
			{
				Number:     3,
				FieldName:  "MinSignatures",
				Name:       "Anzahl Signaturen mindestens",
				Version:    1,
				Type:       DE,
				Format:     num,
				Length:     "1",
				Status:     M,
				Count:      1,
				Limitation: "0, 1, 2, 3",
			},
			{
				Number:     4,
				FieldName:  "SecurityClass",
				Name:       "Sicherheitsklasse",
				Version:    1,
				Type:       DE,
				Format:     code,
				Length:     "1",
				Status:     M,
				Count:      1,
				Limitation: "0, 1, 2, 3, 4",
			},
			{
				Number:    5,
				FieldName: "Params",
				Name:      "Parameter Kontoumsätze/Zeitraum",
				Version:   2,
				Type:      DEG,
				Format:    composed,
				Status:    M,
				Count:     1,
			},
		},
	},
}
