// Code generated by *generator.VersionedSegmentUnmarshalerGenerator; DO NOT EDIT.

package segment

import (
	"bytes"
	"fmt"

	"github.com/mitch000001/go-hbci/element"
)

var (
	_	BankSegment	= &AccountBalanceResponseSegmentV5{}
	_	BankSegment	= &AccountBalanceResponseSegmentV6{}
	_	BankSegment	= &AccountBalanceResponseSegmentV7{}
	_	BankSegment	= &AccountBalanceResponseSegmentV8{}
)

func init() {
	v5 := AccountBalanceResponseSegmentV5{}
	KnownSegments.mustAddToIndex(VersionedSegment{v5.ID(), v5.Version()}, func() Segment { return &AccountBalanceResponseSegmentV5{} })
	v6 := AccountBalanceResponseSegmentV6{}
	KnownSegments.mustAddToIndex(VersionedSegment{v6.ID(), v6.Version()}, func() Segment { return &AccountBalanceResponseSegmentV6{} })
	v7 := AccountBalanceResponseSegmentV7{}
	KnownSegments.mustAddToIndex(VersionedSegment{v7.ID(), v7.Version()}, func() Segment { return &AccountBalanceResponseSegmentV7{} })
	v8 := AccountBalanceResponseSegmentV8{}
	KnownSegments.mustAddToIndex(VersionedSegment{v8.ID(), v8.Version()}, func() Segment { return &AccountBalanceResponseSegmentV8{} })
}

func (a *AccountBalanceResponseSegment) UnmarshalHBCI(value []byte) error {
	elements, err := ExtractElements(value)
	if err != nil {
		return err
	}
	header := &element.SegmentHeader{}
	err = header.UnmarshalHBCI(elements[0])
	if err != nil {
		return err
	}
	var segment AccountBalanceResponse
	switch header.Version.Val() {
	case 5:
		segment = &AccountBalanceResponseSegmentV5{}
		err = segment.UnmarshalHBCI(value)
		if err != nil {
			return err
		}
	case 6:
		segment = &AccountBalanceResponseSegmentV6{}
		err = segment.UnmarshalHBCI(value)
		if err != nil {
			return err
		}
	case 7:
		segment = &AccountBalanceResponseSegmentV7{}
		err = segment.UnmarshalHBCI(value)
		if err != nil {
			return err
		}
	case 8:
		segment = &AccountBalanceResponseSegmentV8{}
		err = segment.UnmarshalHBCI(value)
		if err != nil {
			return err
		}
	default:
		return fmt.Errorf("unknown segment version: %d", header.Version.Val())
	}
	a.AccountBalanceResponse = segment
	return nil
}

func (a *AccountBalanceResponseSegmentV5) UnmarshalHBCI(value []byte) error {
	elements, err := ExtractElements(value)
	if err != nil {
		return err
	}
	if len(elements) == 0 {
		return fmt.Errorf("malformed marshaled value: no elements extracted")
	}
	seg, err := SegmentFromHeaderBytes(elements[0], a)
	if err != nil {
		return err
	}
	a.Segment = seg
	if len(elements) > 1 && len(elements[1]) > 0 {
		a.AccountConnection = &element.AccountConnectionDataElement{}
		err = a.AccountConnection.UnmarshalHBCI(elements[1])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountConnection: %w", err)
		}
	}
	if len(elements) > 2 && len(elements[2]) > 0 {
		a.AccountProductName = &element.AlphaNumericDataElement{}
		err = a.AccountProductName.UnmarshalHBCI(elements[2])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountProductName: %w", err)
		}
	}
	if len(elements) > 3 && len(elements[3]) > 0 {
		a.AccountCurrency = &element.CurrencyDataElement{}
		err = a.AccountCurrency.UnmarshalHBCI(elements[3])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountCurrency: %w", err)
		}
	}
	if len(elements) > 4 && len(elements[4]) > 0 {
		a.BookedBalance = &element.BalanceDataElement{}
		err = a.BookedBalance.UnmarshalHBCI(elements[4])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookedBalance: %w", err)
		}
	}
	if len(elements) > 5 && len(elements[5]) > 0 {
		a.EarmarkedBalance = &element.BalanceDataElement{}
		err = a.EarmarkedBalance.UnmarshalHBCI(elements[5])
		if err != nil {
			return fmt.Errorf("error unmarshaling EarmarkedBalance: %w", err)
		}
	}
	if len(elements) > 6 && len(elements[6]) > 0 {
		a.CreditLimit = &element.AmountDataElement{}
		err = a.CreditLimit.UnmarshalHBCI(elements[6])
		if err != nil {
			return fmt.Errorf("error unmarshaling CreditLimit: %w", err)
		}
	}
	if len(elements) > 7 && len(elements[7]) > 0 {
		a.AvailableAmount = &element.AmountDataElement{}
		err = a.AvailableAmount.UnmarshalHBCI(elements[7])
		if err != nil {
			return fmt.Errorf("error unmarshaling AvailableAmount: %w", err)
		}
	}
	if len(elements) > 8 && len(elements[8]) > 0 {
		a.UsedAmount = &element.AmountDataElement{}
		err = a.UsedAmount.UnmarshalHBCI(elements[8])
		if err != nil {
			return fmt.Errorf("error unmarshaling UsedAmount: %w", err)
		}
	}
	if len(elements) > 9 && len(elements[9]) > 0 {
		a.BookingDate = &element.DateDataElement{}
		err = a.BookingDate.UnmarshalHBCI(elements[9])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookingDate: %w", err)
		}
	}
	if len(elements) > 10 && len(elements[10]) > 0 {
		a.BookingTime = &element.TimeDataElement{}
		err = a.BookingTime.UnmarshalHBCI(elements[10])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookingTime: %w", err)
		}
	}
	if len(elements) > 11 && len(elements[11]) > 0 {
		a.DueDate = &element.DateDataElement{}
		if len(elements)+1 > 11 {
			err = a.DueDate.UnmarshalHBCI(bytes.Join(elements[11:], []byte("+")))
		} else {
			err = a.DueDate.UnmarshalHBCI(elements[11])
		}
		if err != nil {
			return fmt.Errorf("error unmarshaling DueDate: %w", err)
		}
	}
	return nil
}

func (a *AccountBalanceResponseSegmentV6) UnmarshalHBCI(value []byte) error {
	elements, err := ExtractElements(value)
	if err != nil {
		return err
	}
	if len(elements) == 0 {
		return fmt.Errorf("malformed marshaled value: no elements extracted")
	}
	seg, err := SegmentFromHeaderBytes(elements[0], a)
	if err != nil {
		return err
	}
	a.Segment = seg
	if len(elements) > 1 && len(elements[1]) > 0 {
		a.AccountConnection = &element.AccountConnectionDataElement{}
		err = a.AccountConnection.UnmarshalHBCI(elements[1])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountConnection: %w", err)
		}
	}
	if len(elements) > 2 && len(elements[2]) > 0 {
		a.AccountProductName = &element.AlphaNumericDataElement{}
		err = a.AccountProductName.UnmarshalHBCI(elements[2])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountProductName: %w", err)
		}
	}
	if len(elements) > 3 && len(elements[3]) > 0 {
		a.AccountCurrency = &element.CurrencyDataElement{}
		err = a.AccountCurrency.UnmarshalHBCI(elements[3])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountCurrency: %w", err)
		}
	}
	if len(elements) > 4 && len(elements[4]) > 0 {
		a.BookedBalance = &element.BalanceDataElement{}
		err = a.BookedBalance.UnmarshalHBCI(elements[4])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookedBalance: %w", err)
		}
	}
	if len(elements) > 5 && len(elements[5]) > 0 {
		a.EarmarkedBalance = &element.BalanceDataElement{}
		err = a.EarmarkedBalance.UnmarshalHBCI(elements[5])
		if err != nil {
			return fmt.Errorf("error unmarshaling EarmarkedBalance: %w", err)
		}
	}
	if len(elements) > 6 && len(elements[6]) > 0 {
		a.CreditLimit = &element.AmountDataElement{}
		err = a.CreditLimit.UnmarshalHBCI(elements[6])
		if err != nil {
			return fmt.Errorf("error unmarshaling CreditLimit: %w", err)
		}
	}
	if len(elements) > 7 && len(elements[7]) > 0 {
		a.AvailableAmount = &element.AmountDataElement{}
		err = a.AvailableAmount.UnmarshalHBCI(elements[7])
		if err != nil {
			return fmt.Errorf("error unmarshaling AvailableAmount: %w", err)
		}
	}
	if len(elements) > 8 && len(elements[8]) > 0 {
		a.UsedAmount = &element.AmountDataElement{}
		err = a.UsedAmount.UnmarshalHBCI(elements[8])
		if err != nil {
			return fmt.Errorf("error unmarshaling UsedAmount: %w", err)
		}
	}
	if len(elements) > 9 && len(elements[9]) > 0 {
		a.BookingDate = &element.DateDataElement{}
		err = a.BookingDate.UnmarshalHBCI(elements[9])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookingDate: %w", err)
		}
	}
	if len(elements) > 10 && len(elements[10]) > 0 {
		a.BookingTime = &element.TimeDataElement{}
		err = a.BookingTime.UnmarshalHBCI(elements[10])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookingTime: %w", err)
		}
	}
	if len(elements) > 11 && len(elements[11]) > 0 {
		a.DueDate = &element.DateDataElement{}
		if len(elements)+1 > 11 {
			err = a.DueDate.UnmarshalHBCI(bytes.Join(elements[11:], []byte("+")))
		} else {
			err = a.DueDate.UnmarshalHBCI(elements[11])
		}
		if err != nil {
			return fmt.Errorf("error unmarshaling DueDate: %w", err)
		}
	}
	return nil
}

func (a *AccountBalanceResponseSegmentV7) UnmarshalHBCI(value []byte) error {
	elements, err := ExtractElements(value)
	if err != nil {
		return err
	}
	if len(elements) == 0 {
		return fmt.Errorf("malformed marshaled value: no elements extracted")
	}
	seg, err := SegmentFromHeaderBytes(elements[0], a)
	if err != nil {
		return err
	}
	a.Segment = seg
	if len(elements) > 1 && len(elements[1]) > 0 {
		a.AccountConnection = &element.InternationalAccountConnectionDataElement{}
		err = a.AccountConnection.UnmarshalHBCI(elements[1])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountConnection: %w", err)
		}
	}
	if len(elements) > 2 && len(elements[2]) > 0 {
		a.AccountProductName = &element.AlphaNumericDataElement{}
		err = a.AccountProductName.UnmarshalHBCI(elements[2])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountProductName: %w", err)
		}
	}
	if len(elements) > 3 && len(elements[3]) > 0 {
		a.AccountCurrency = &element.CurrencyDataElement{}
		err = a.AccountCurrency.UnmarshalHBCI(elements[3])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountCurrency: %w", err)
		}
	}
	if len(elements) > 4 && len(elements[4]) > 0 {
		a.BookedBalance = &element.BalanceDataElement{}
		err = a.BookedBalance.UnmarshalHBCI(elements[4])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookedBalance: %w", err)
		}
	}
	if len(elements) > 5 && len(elements[5]) > 0 {
		a.EarmarkedBalance = &element.BalanceDataElement{}
		err = a.EarmarkedBalance.UnmarshalHBCI(elements[5])
		if err != nil {
			return fmt.Errorf("error unmarshaling EarmarkedBalance: %w", err)
		}
	}
	if len(elements) > 6 && len(elements[6]) > 0 {
		a.CreditLimit = &element.AmountDataElement{}
		err = a.CreditLimit.UnmarshalHBCI(elements[6])
		if err != nil {
			return fmt.Errorf("error unmarshaling CreditLimit: %w", err)
		}
	}
	if len(elements) > 7 && len(elements[7]) > 0 {
		a.AvailableAmount = &element.AmountDataElement{}
		err = a.AvailableAmount.UnmarshalHBCI(elements[7])
		if err != nil {
			return fmt.Errorf("error unmarshaling AvailableAmount: %w", err)
		}
	}
	if len(elements) > 8 && len(elements[8]) > 0 {
		a.UsedAmount = &element.AmountDataElement{}
		err = a.UsedAmount.UnmarshalHBCI(elements[8])
		if err != nil {
			return fmt.Errorf("error unmarshaling UsedAmount: %w", err)
		}
	}
	if len(elements) > 9 && len(elements[9]) > 0 {
		a.BookingDate = &element.DateDataElement{}
		err = a.BookingDate.UnmarshalHBCI(elements[9])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookingDate: %w", err)
		}
	}
	if len(elements) > 10 && len(elements[10]) > 0 {
		a.BookingTime = &element.TimeDataElement{}
		err = a.BookingTime.UnmarshalHBCI(elements[10])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookingTime: %w", err)
		}
	}
	if len(elements) > 11 && len(elements[11]) > 0 {
		a.DueDate = &element.DateDataElement{}
		if len(elements)+1 > 11 {
			err = a.DueDate.UnmarshalHBCI(bytes.Join(elements[11:], []byte("+")))
		} else {
			err = a.DueDate.UnmarshalHBCI(elements[11])
		}
		if err != nil {
			return fmt.Errorf("error unmarshaling DueDate: %w", err)
		}
	}
	return nil
}

func (a *AccountBalanceResponseSegmentV8) UnmarshalHBCI(value []byte) error {
	elements, err := ExtractElements(value)
	if err != nil {
		return err
	}
	if len(elements) == 0 {
		return fmt.Errorf("malformed marshaled value: no elements extracted")
	}
	seg, err := SegmentFromHeaderBytes(elements[0], a)
	if err != nil {
		return err
	}
	a.Segment = seg
	if len(elements) > 1 && len(elements[1]) > 0 {
		a.AccountConnection = &element.InternationalAccountConnectionDataElement{}
		err = a.AccountConnection.UnmarshalHBCI(elements[1])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountConnection: %w", err)
		}
	}
	if len(elements) > 2 && len(elements[2]) > 0 {
		a.AccountProductName = &element.AlphaNumericDataElement{}
		err = a.AccountProductName.UnmarshalHBCI(elements[2])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountProductName: %w", err)
		}
	}
	if len(elements) > 3 && len(elements[3]) > 0 {
		a.AccountCurrency = &element.CurrencyDataElement{}
		err = a.AccountCurrency.UnmarshalHBCI(elements[3])
		if err != nil {
			return fmt.Errorf("error unmarshaling AccountCurrency: %w", err)
		}
	}
	if len(elements) > 4 && len(elements[4]) > 0 {
		a.BookedBalance = &element.BalanceDataElement{}
		err = a.BookedBalance.UnmarshalHBCI(elements[4])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookedBalance: %w", err)
		}
	}
	if len(elements) > 5 && len(elements[5]) > 0 {
		a.EarmarkedBalance = &element.BalanceDataElement{}
		err = a.EarmarkedBalance.UnmarshalHBCI(elements[5])
		if err != nil {
			return fmt.Errorf("error unmarshaling EarmarkedBalance: %w", err)
		}
	}
	if len(elements) > 6 && len(elements[6]) > 0 {
		a.CreditLimit = &element.AmountDataElement{}
		err = a.CreditLimit.UnmarshalHBCI(elements[6])
		if err != nil {
			return fmt.Errorf("error unmarshaling CreditLimit: %w", err)
		}
	}
	if len(elements) > 7 && len(elements[7]) > 0 {
		a.AvailableAmount = &element.AmountDataElement{}
		err = a.AvailableAmount.UnmarshalHBCI(elements[7])
		if err != nil {
			return fmt.Errorf("error unmarshaling AvailableAmount: %w", err)
		}
	}
	if len(elements) > 8 && len(elements[8]) > 0 {
		a.UsedAmount = &element.AmountDataElement{}
		err = a.UsedAmount.UnmarshalHBCI(elements[8])
		if err != nil {
			return fmt.Errorf("error unmarshaling UsedAmount: %w", err)
		}
	}
	if len(elements) > 9 && len(elements[9]) > 0 {
		a.BookingDate = &element.DateDataElement{}
		err = a.BookingDate.UnmarshalHBCI(elements[9])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookingDate: %w", err)
		}
	}
	if len(elements) > 10 && len(elements[10]) > 0 {
		a.BookingTime = &element.TimeDataElement{}
		err = a.BookingTime.UnmarshalHBCI(elements[10])
		if err != nil {
			return fmt.Errorf("error unmarshaling BookingTime: %w", err)
		}
	}
	if len(elements) > 11 && len(elements[11]) > 0 {
		a.DueDate = &element.DateDataElement{}
		err = a.DueDate.UnmarshalHBCI(elements[11])
		if err != nil {
			return fmt.Errorf("error unmarshaling DueDate: %w", err)
		}
	}
	if len(elements) > 12 && len(elements[12]) > 0 {
		a.SeizableAfterMonth = &element.AmountDataElement{}
		if len(elements)+1 > 12 {
			err = a.SeizableAfterMonth.UnmarshalHBCI(bytes.Join(elements[12:], []byte("+")))
		} else {
			err = a.SeizableAfterMonth.UnmarshalHBCI(elements[12])
		}
		if err != nil {
			return fmt.Errorf("error unmarshaling SeizableAfterMonth: %w", err)
		}
	}
	return nil
}
